### ISSUE TITLE
Extend Yarel with booleans

### ISSUE THREAD

**Issue by st159231** [yarel-di/yarel#29]
Besides integers it is usefull to have functions that work on booleans.
This requires a complete updating of the function signatures.
For example:
int, bool -> bool, int
would be the correct type for the transposition.

**Comment by st159231** [comment]
Beware that merging the branch develop-booleans, relative to this issue, requires a major refactoring of the branch develop.

**Comment by LucaRoversi** [comment]
Riccardo successfully extended an experimental and minimal version of Yarel  with booleans. Considered that such an update is disruptive, concerning both syntax and semantics, the branch will never be merged in develop.
